### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by HynlorXD** [Evolution-WoW/Migrate-your-character#12]
Character name there:Ulquiorra
Character name here:Ulquiorra
Class and spec (main spec only):Death Knight (Unholy)
Profession (1 primary max skill only):JewelCrafting
Server from where you want to migrate:WoW Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
![image_2022-04-25_155650740](https://user-images.githubusercontent.com/104220970/165093611-054a1bf9-3985-4e23-bfe5-88541557fe0f.png)
![image_2022-04-25_155723052](https://user-images.githubusercontent.com/104220970/165093700-8ae856c1-97b4-48b2-853b-d60bed8f842d.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email. Rageless#3969

**Comment by Ragelezz** [comment]
Done
