### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by tarik1504** [Evolution-WoW/Migrate-your-character#16]
Character name there: Hakija
Character name here: Tarix
Class and spec (main spec only): Fury Warrior
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
https://drive.google.com/file/d/11cR_DCK_R4Ht-kgrUHJ_tKzhNWwFugow/view?usp=sharing
https://drive.google.com/file/d/1tW8sN1-kVmDkJJml1W1UzTbtdGgJFJJO/view?usp=sharing

**Comment by Ragelezz** [comment]
Ping me on discord with your account email. Rageless#3969

**Comment by Ragelezz** [comment]
Let me know when you've created your account on discord, currently you didn't so I can't migrate your char.

**Comment by Ragelezz** [comment]
done
