### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by doom81** [Evolution-WoW/Migrate-your-character#17]
Character name there: Doomx
Character name here: Doom
Class and spec (main spec only): Arms Warrior, Survival Hunter here if possible
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Uwow x5
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
https://imgur.com/Q4HwgKA / https://imgur.com/UiDOXv7

**Comment by Ragelezz** [comment]
done just the warrior, only 1 char at the moment.
