### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Dudulekarnik** [Evolution-WoW/Migrate-your-character#18]
Character name there:Dudulekarnik
Character name here:Dudulekarnik
Class and spec (main spec only):Druid , Restoration
Profession (1 primary max skill only):Alchemy
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
![obrázok_2022-04-26_200136548](https://user-images.githubusercontent.com/104456845/165363386-d39dd442-f464-4cf8-8fdc-8e7a0060fc03.png)
![image](https://user-images.githubusercontent.com/104456845/165364218-d4fa4916-9677-414d-b4f1-4bb287f9946f.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
done
