### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Vrtulnik** [Evolution-WoW/Migrate-your-character#22]
Character name there: UndryLegun
Character name here: Balfor
Class and spec (main spec only): Druid Feral
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Wow Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
Well, i tried to yell it and i insta got kicked and muted for 7 days so hope u can count it as a proof  xD.
![image](https://user-images.githubusercontent.com/104535775/165648365-5ccc5719-85c9-4b4a-9a12-296cd51e539e.png)
![image](https://user-images.githubusercontent.com/104535775/165648868-12fd6642-dbbd-4cf7-bbcf-7f77bd6e2da8.png)

![image](https://user-images.githubusercontent.com/104535775/165648589-4c919c32-01cd-41da-9753-322286f75b2f.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
done
