### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by NestXx** [Evolution-WoW/Migrate-your-character#23]
Character name there: Nestx
Character name here: Nestx
Class and spec (main spec only): Fury Warrior
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Firestorm WoW
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough): https://imgur.com/a/k3PG0cu

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
No account create, let me know when you've created your account so I can transfer the char.

**Comment by Ragelezz** [comment]
done
