### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Cristina1005** [Evolution-WoW/Migrate-your-character#24]
Character name there: Snow
Character name here: Snow
Class and spec (main spec only): BM
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: WoW Freakz
![image_2022-04-28_110439712](https://user-images.githubusercontent.com/104563483/165729215-f46320bf-189b-4451-a254-d47f0c8d769f.png)

Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
