### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Issac-Netero** [Evolution-WoW/Migrate-your-character#25]
Character name there: Neteriya (Female Nightelf)
Character name here: Neteriya (Female Nightelf)
Class and spec (main spec only): Demon Hunter Havoc (dps)
Profession (1 primary max skill only): Enchanting
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
![1](https://user-images.githubusercontent.com/46303433/165729608-db7a4748-2bcb-45f3-bbe7-a2caff4eb998.png)
![2](https://user-images.githubusercontent.com/46303433/165729706-f00fc668-3f95-4c38-853e-bf744195cef0.png)
![3](https://user-images.githubusercontent.com/46303433/165729722-65bd6552-e356-49b4-bc26-5a96c4b554a1.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
done
