### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Umbersun** [Evolution-WoW/Migrate-your-character#27]
Character name there: Umbersun
Character name here: Umbersun
Class and spec (main spec only): Frost
Profession (1 primary max skill only): Tailoring
![Screenshot WoW](https://user-images.githubusercontent.com/104566052/165738029-87ec0a87-cb42-4c7b-9eb4-9288d37a4dcd.jpg)

Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
