### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by alezgubilici** [Evolution-WoW/Migrate-your-character#29]
Character name there: Iriis
Character name here: Iriis
Class and spec (main spec only): Holy
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ing
![screenshot wow Alexandra](https://user-images.githubusercontent.com/104575508/165767709-1f4e164e-ea94-4e18-92fb-a32d88a62503.jpg)
ame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
