### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by rosaraul** [Evolution-WoW/Migrate-your-character#30]
Character name there: Hadoukenx
Character name here: Hadoukenx
Class and spec (main spec only): Restoration Druid
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Freakz
Proofs of you playing there: Character list from Freakz login site
![Screenshot_1](https://user-images.githubusercontent.com/100857860/165775951-0ce5b9e7-28fc-4919-a71c-09130d6dcaf3.png)
 (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
done
