### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by blanarife** [Evolution-WoW/Migrate-your-character#33]
Character name there: Welelel
Character name here: Welelel
Class and spec (main spec only): Blood Death Knight
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Uwow
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

https://imgur.com/a/Tef1eYq

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
done
