### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by vasilescu-stefan** [Evolution-WoW/Migrate-your-character#35]
Character name there:Sesyan
Character name here:Sesyan
Class and spec (main spec only):Warlock Affliction
Profession (1 primary max skill only):Alchemy
Server from where you want to migrate: UWOW
![ss1](https://user-images.githubusercontent.com/79272338/165817232-bd3cb7ca-2bc4-4f2a-9452-90f81572fcfb.png)
![ss2](https://user-images.githubusercontent.com/79272338/165817252-4cc4d942-c33c-4149-87da-c88d39dc7d09.png)
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
done
