### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Daphneqt** [Evolution-WoW/Migrate-your-character#37]
Character name there: Daphne
Character name here: Daphne
Class and spec (main spec only): Rogue Assassination
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
https://imgur.com/a/QG4HVeP

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969

**Comment by Ragelezz** [comment]
done
