### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Barbutqt** [Evolution-WoW/Migrate-your-character#39]
Character name there: Barbut
Character name here: Barbut
Class and spec (main spec only): Death Knight (Blood)
Profession (1 primary max skill only): Engineering
Server from where you want to migrate: Firestorm
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on
 that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough): 
![Untitled](https://user-images.githubusercontent.com/104596512/165844365-abeb2a1c-ff7f-45fc-906a-459d3aa46937.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
