### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Lawlexan** [Evolution-WoW/Migrate-your-character#4]
Character name there:Killblade
Character name here:Killblade
Class and spec (main spec only):assassination
Profession (1 primary max skill only):alchemy
Server from where you want to migrate:freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
![image](https://user-images.githubusercontent.com/103905717/163875708-f2fc6b13-0cc7-4a7a-81e2-848fec30fa4d.png)
![image](https://user-images.githubusercontent.com/103905717/163876425-64d49fe9-affa-487c-9e7c-ef5fee2cb91a.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email. Rageless#3969

**Comment by Ragelezz** [comment]
done
