### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Gorend** [Evolution-WoW/Migrate-your-character#40]
Character name there: Corazzo
Character name here: Gorend
Class and spec (main spec only): Paladin Holy
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Firestorm
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
https://imgur.com/a/tYYUMoL
![Screenshot_416](https://user-images.githubusercontent.com/104596542/165841466-65654649-9561-45be-8430-810a19c115a9.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
