### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by raulcoroiu** [Evolution-WoW/Migrate-your-character#44]
Character name there:Floki
Character name here:Floki
Class and spec (main spec only):Windwalker
Profession (1 primary max skill only):Alchemy
Server from where you want to migrate:Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
![leagion](https://user-images.githubusercontent.com/87768731/165919253-911eaa35-faa3-4a1a-8556-9a2c7c67e0bf.jpg)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
