### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by radelfane** [Evolution-WoW/Migrate-your-character#48]
Character name there: Pugnus
Character name here: Pugnus
Class and spec (main spec only): Mage fire
Profession (1 primary max skill only): Enchanting
Server from where you want to migrate: freakz
Proofs of you playing there:
![Screenshot_44](https://user-images.githubusercontent.com/104635621/165957448-8323eeb3-96a7-41ff-93e5-b35442b60e51.png)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
Make sure that you already have the account created here.

**Comment by Ragelezz** [comment]
done
