### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by itsyaboyChrona** [Evolution-WoW/Migrate-your-character#49]
Character name there: Nyndra
Character name here: Nyndra
Class and spec (main spec only): Boomy Druid
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Freakz
![n een](https://user-images.githubusercontent.com/104629195/165958293-27e67707-96e0-4e96-b561-907bac962ceb.png)

Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969
Make sure that you already have the account created here.

**Comment by Ragelezz** [comment]
done
