### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by seductiveMind** [Evolution-WoW/Migrate-your-character#5]
Character name there: Cosette
Character name here: Cosette
Class and spec (main spec only): Arms
Profession (1 primary max skill only): Tailoring
Server from where you want to migrate: UWow
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
![IMG_20220419_123925](https://user-images.githubusercontent.com/96945498/163937788-dcff0f11-a116-47f3-8b21-1a42c290f355.jpg)
![WoWScrnShot_041922_123635](https://user-images.githubusercontent.com/96945498/163937822-265d96fa-7c36-435a-8c17-d67851fa8077.jpg)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email. Rageless#3969

**Comment by Ragelezz** [comment]
done
