### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by bluesnow5422** [Evolution-WoW/Migrate-your-character#53]
Character name there:crit
Character name here: i dont have one yet but crit plz
Class and spec (main spec only): Balance druid
Profession (1 primary max skill only):Herbalism
What race you want here (can be Allied Races too): Female troll
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and mark
![Screenshot_1](https://user-images.githubusercontent.com/104644881/165988723-91f1b6db-37e8-424c-ad7b-5551d4e6e8f2.jpg)
ed as closed.  The account is iamsimple1993@outlook.com. Not the email that i am using atm ty

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862
