### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by SadrisMorgana** [Evolution-WoW/Migrate-your-character#54]
Character name there: Morgana
Character name here: Morgana
Class and spec (main spec only): Blood Death Knight
Profession (1 primary max skill only): Alchemy
What race you want here (can be Allied Races too): Female Blood Elf
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed. 
![WoWScrnShot_042922_115019](https://user-images.githubusercontent.com/104645000/165988680-04ce2b23-3f08-4746-9317-a42002022670.jpg)

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862
