### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by joemunchies** [Evolution-WoW/Migrate-your-character#55]
Character name there: Hugocopter
Character name here: Hugocopter
Class and spec (main spec only): Demon Hunter Havoc
Profession (1 primary max skill only): Enchanting
What race you want here (can be Allied Races too): Blood Elf
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed. 
![unknown](https://user-images.githubusercontent.com/26780344/165996153-bc020d41-0c88-4d25-9413-851298628379.png)

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862

**Comment by Ragelezz** [comment]
done
