### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Marin344** [Evolution-WoW/Migrate-your-character#59]
Character name there:Coccau
Character name here:Cocau
Class and spec (main spec only):Monk-Windwalker
Profession (1 primary max skill only):Alchemy
What race you want here (can be Allied Races too):Pandaren
Server from where you want to migrate:Firestorm
![WoWScrnShot_043022_001253](https://user-images.githubusercontent.com/104654774/166070921-776d859b-9796-463e-8972-556a0a09eefd.jpg)
![WoWScrnShot_043022_001954](https://user-images.githubusercontent.com/104654774/166070923-c64236cf-37ce-47f9-b0e1-229f277e3ddf.jpg)
![WoWScrnShot_043022_001253](https://user-images.githubusercontent.com/104654774/166071058-e6401b53-b549-4e6b-b4e7-0c270b8a07f7.jpg)
![WoWScrnShot_043022_001954](https://user-images.githubusercontent.com/104654774/166071059-5e17be99-50df-49ec-9d31-289c851a5aec.jpg)

Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862
