### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by OitzahBarsana** [Evolution-WoW/Migrate-your-character#6]
Character name there: Ooaiedahots
Character name here: Ooaiedaboomy
Class and spec (main spec only): Balance
Profession (1 primary max skill only): Alchemy
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server
![Character_selection](https://user-images.githubusercontent.com/104162698/164525041-371faeec-2f43-4848-b4c3-71e54bf10b28.JPG)
![Evolution_character](https://user-images.githubusercontent.com/104162698/164525074-31a979ae-ee29-4628-8163-0adc2ef48776.JPG)

**Comment by Ragelezz** [comment]
Ping me on discord with your account email. Rageless#3969

**Comment by Ragelezz** [comment]
done
