### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Hommie01** [Evolution-WoW/Migrate-your-character#60]
Character name there: Bulldozeru
Character name here: Bulldozer
Class and spec (main spec only): Restoration Druid
Profession (1 primary max skill only): Enchanting
What race you want here (can be Allied Races too): Tauren
Server from where you want to migrate: Wow Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
![Untitled](https://user-images.githubusercontent.com/104656750/166075758-045cee6a-ebed-486b-9638-159bc8beb272.png)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969 Make sure to have the account created here.

**Comment by Ragelezz** [comment]
done
