### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by HealingWavee** [Evolution-WoW/Migrate-your-character#61]
Character name there: Healingwave
Character name here: Healingwave
Class and spec (main spec only):Shaman Restoration
Profession (1 primary max skill only):Enchanting
What race you want here (can be Allied Races too):Tauren
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
https://ibb.co/hXx92CQ
Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Ragelezz** [comment]
Ping me on discord with your account email and the link to this request so I know who you are. Rageless#3969 Make sure to have the account created here.

**Comment by Ragelezz** [comment]
done
