### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Juhziz** [Evolution-WoW/Migrate-your-character#62]
Character name there: Vagabond
Character name here: Kek
Class and spec (main spec only): Warlock - Destruction
Profession (1 primary max skill only): Alchemy
What race you want here (can be Allied Races too): Alliance - Void Elf Female - with customize
Server from where you want to migrate: Freakzy
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
you know me who i am :D
https://i.imgur.com/8PnVOJt.png
Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Ragelezz** [comment]
done
