### ISSUE TITLE
[Migration] Malefique 

### ISSUE THREAD

**Issue by Malefique96** [Evolution-WoW/Migrate-your-character#63]
Character name there: Malefique
Character name here: Malefique
Class and spec (main spec only): Druid /Restoration
Profession (1 primary max skill only):  Alchemy. 
What race you want here (can be Allied Races too): Tauren 
Server from where you want to migrate: Freakz 
Proofs of you playing there: https://imgur.com/4hLylRr

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Ragelezz** [comment]
ping me on discord with the account's mail

**Comment by Ragelezz** [comment]
done
