### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by negrilaovidiu** [Evolution-WoW/Migrate-your-character#65]
Character name there: Liviut
Character name here: Liviut
Class and spec (main spec only):Hunter, BM
Profession (1 primary max skill only):Alchemy
What race you want here (can be Allied Races too): Human
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION 
CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

![liviut](https://user-images.githubusercontent.com/45025741/166108466-0dfc1833-327f-46b9-8c81-dd01e7111492.png)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862
