### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Diussx** [Evolution-WoW/Migrate-your-character#66]
Character name there: Dius
Character name here: Dius
Class and spec (main spec only): Rogue Assasination
Profession (1 primary max skill only): Enchanting
What race you want here (can be Allied Races too): Void Elf
Server from where you want to migrate: WowFreakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed. 
![New Bitmap Image (2)](https://user-images.githubusercontent.com/104701559/166127105-ffb58306-c6af-4474-ada5-f5e0a3b54e22.jpg)
![New Bitmap Image](https://user-images.githubusercontent.com/104701559/166127107-a1cf64a3-ca4a-445e-94d2-d81dd84200a0.jpg)

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862

**Comment by Diussx** [comment]
Nu reusesc, sau ceva nu fac bine

Clyde
BOT
 — Today at 21:59
Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends.****

**Comment by Denimz92** [comment]
I've received your request and replied there.
