### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Davotth** [Evolution-WoW/Migrate-your-character#67]
Character name there:Garddon
Character name here:Garddon
Class and spec (main spec only):Warrior fury
Profession (1 primary max skill only): alchemy
What race you want here (can be Allied Races too):Orc
Server from where you want to migrate:Freaks
![download (1)](https://user-images.githubusercontent.com/104720179/166145210-fd6f1d6d-afda-420c-88ae-5c1d4845f5f0.png)
![download (2)](https://user-images.githubusercontent.com/104720179/166145217-c8866328-9e69-4d52-a74d-d79d7ad991c8.png)

Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862
