### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by Liinx** [Evolution-WoW/Migrate-your-character#68]
Character name there: Sharazar
Character name here: Sharazar
Class and spec (main spec only): Vengeance Demon Hunter
Profession (1 primary max skill only): Engineering
What race you want here (can be Allied Races too): Male Blood Elf
Server from where you want to migrate: WoW Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)
![ezgif-3-fa40cf0fbb](https://user-images.githubusercontent.com/46263719/166145610-25bacfa2-ec7f-4b75-9a24-ea290a022eca.png)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862
