### ISSUE TITLE
[Migration]

### ISSUE THREAD

**Issue by iustinica** [Evolution-WoW/Migrate-your-character#69]
Character name there: Liviutmonk
Character name here: Liviutmonk
Class and spec (main spec only):Monk; Brewmaster
Profession (1 primary max skill only): Alchemy
What race you want here (can be Allied Races too): Nightelf
Server from where you want to migrate: Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

![iustina](https://user-images.githubusercontent.com/104727918/166153708-32b16f41-d45d-48d9-a2cf-a2ac65ca335b.png)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.

**Comment by Denimz92** [comment]
PM me on Discord with the account name on Denim#1862
