### ISSUE TITLE
[Migration] Single Character

### ISSUE THREAD

**Issue by Zelatus** [Evolution-WoW/Migrate-your-character#77]
Character name there: Dungoro
Character name here: Zelatus
Profession (1 primary max skill only): Enchanting
What race you want here (can be Allied Races too): Blood Elf
Server from where you want to migrate: WoW Freakz Warsong/Shadowsong
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.
![WoWScrnShot_110621_124020](https://user-images.githubusercontent.com/105654059/168624117-9f40af19-fca5-48c6-9bf7-95d5f55b765a.jpg)

**Comment by Ragelezz** [comment]
New screenshot please, BfA was on freakz months ago.

**Comment by Zelatus** [comment]
I attach new screenshots. In Shadowlands I only leveled my DH.
![WoWScrnShot_051622_211942](https://user-images.githubusercontent.com/105654059/168657591-c222a1fc-f3d0-47b0-aa59-2329b0be038d.jpg)
![WoWScrnShot_051622_212004](https://user-images.githubusercontent.com/105654059/168657615-3ea55bd9-dd89-4cd2-b4de-b7f58982f620.jpg)
.

**Comment by Ragelezz** [comment]
ping me on discord with your email on Evolution, Rageless#3969

**Comment by Ragelezz** [comment]
done
