### ISSUE TITLE
[Migration] Single Character

### ISSUE THREAD

**Issue by Zackiff** [Evolution-WoW/Migrate-your-character#79]
Character name there: Zackiff
Character name here: Zackiff
Profession (1 primary max skill only): Alchemy
What race you want here (can be Allied Races too): Human
Server from where you want to migrate: Outland-EU (retail)
Proofs of you playing there: My sub expired so I can't log in but here's the main menu screenshot

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed
![Screenshot_1](https://user-images.githubusercontent.com/97764389/169483341-3c65994c-ee17-459f-a9ae-902d185eef8f.jpg)
.

**Comment by Ragelezz** [comment]
ping me on discord with your email here

**Comment by Ragelezz** [comment]
done
