### ISSUE TITLE
[Migration] Single Character

### ISSUE THREAD

**Issue by Xonthrias** [Evolution-WoW/Migrate-your-character#80]
Character name there: Totemwiener
Character name here: Totemwiener
Profession (1 primary max skill only): enchanting
What race you want here (can be Allied Races too): Orc
Server from where you want to migrate: WoW Freakz
Proofs of you playing there: Char selection screen & ingame yelling EVOLUTION CHARACTER on that server (If you are coming from WoW Freakz, you don't need to yell ingame since you get muted, character selection screen proof is enough)

Due to our transfer system, we encourage you not to access the account until the process is completed and marked as closed.
![totemwiener freakz](https://user-images.githubusercontent.com/106013624/169690358-4188a2ad-cd00-4d00-814d-841efad46874.PNG)
![totemwiener in game freakz](https://user-images.githubusercontent.com/106013624/169690366-6dd0cf3b-cc75-47b1-b419-ab50ef924cd4.PNG)

**Comment by Ragelezz** [comment]
ping me on discord with your email here
